version: '3'

services:
  crontab:
    image: "node:8"
    user: "root"
    working_dir: /home/node/app
    volumes:
      - ./crontab:/home/node/app
    networks:
      - shared
    command: "npm start"
  db:
    image: mysql
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PW}
  #    - MYSQL_DATABASE=gogo
  #    - MYSQL_PASSWORD=gogo
  #    - MYSQL_USER=gogo
    networks:
      - shared
    volumes:
      - db-data:/var/lib/mysql:rw
      # for sql dumps
      - ./sql-dumps:/var/sql-dumps:rw
#  broker:
#    image: rabbitmq:3-management
#    expose:
#    # rabbitmq
#      - 5672
#    # rabbitmq manager
#      - 15672
#    environment:
#      - RABBITMQ_DEFAULT_PASS=pass
#      - RABBITMQ_DEFAULT_USER=user
#      #RABBITMQ_DEFAULT_VHOST: vhost
#    networks:
#      - shared
#      - private
#  web:
#    image: nginx
#    volumes:
#     - ./mysite.conf:/etc/nginx/conf.d/mysite.conf
#    expose:
#     - 80
#    environment:
#      - NGINX_HOST=playground.${HOSTNAME}
#      - NGINX_PORT=80
#      - VIRTUAL_HOST=playground.${HOSTNAME}
#      - LETSENCRYPT_HOST=playground.${HOSTNAME}
#      - LETSENCRYPT_EMAIL=${EMAIL}
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
#    networks:
#      - shared
#      - reverse-proxy
#  messenger:
#    image: "node:8"
#    user: "root"
#    working_dir: /home/node/app
#    volumes:
#      - ./consumer/messenger:/home/node/app
#    networks:
#      - private
#      - shared
#    command: "npm start"

volumes:
  db-data: {}

networks:
  reverse-proxy:
    external:
      name: reverseproxy_default
  shared:
    external:
      name: shared
  private:
    driver: bridge