version: '3'

services:
  rabbit:
    image: rabbitmq:3-management
    expose:
      - 5672
      - 15672
    environment:
      - RABBITMQ_DEFAULT_PASS=pass
      - RABBITMQ_DEFAULT_USER=user
      #RABBITMQ_DEFAULT_VHOST: vhost
    networks:
      - shared
      - private
# tried to expose the rabbitmq management browser app, doesn't work because of conflicting http basic auths
#  web:
#    image: nginx
#    volumes:
#     - ./mysite.conf:/etc/nginx/conf.d/mysite.conf
#    expose:
#     - 80
#    environment:
#      - NGINX_HOST=playground.${HOSTNAME}
#      - NGINX_PORT=80
#      - VIRTUAL_HOST=playground.${HOSTNAME}
#      - LETSENCRYPT_HOST=playground.${HOSTNAME}
#      - LETSENCRYPT_EMAIL=${EMAIL}
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
#    networks:
#      - shared
#      - reverse-proxy
  messenger:
    image: "node:8"
    user: "root"
    working_dir: /home/node/app
    volumes:
      - consumer/messenger:/home/node/app
    networks:
      - private

networks:
  reverse-proxy:
    external:
      name: reverseproxy_default
  shared:
    external:
      name: shared
  private:
    driver: bridge